### ISSUE TITLE
Order CVE Identifiers by release, not by issue received.

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/security#44]
CVE's [2019-11247 and 2019-11249](https://groups.google.com/forum/#!topic/kubernetes-security-announce/vUtEcSEY6SM) were released on 8/5/19, while [2019-11248](https://groups.google.com/forum/#!topic/kubernetes-security-announce/pKELclHIov8) was released on 8/6/19. Giving CVEs identifiers based on the issue order can disclose the presence of undisclosed security issues, and should be avoided.

**Comment by joelsmith** [comment]
This suggestion isn't very feasible since we have to prepare our messaging in advance and we can't reliably predict when a given issue will be disclosed. A disclosure may be delayed for any number of reasons.

Perhaps we could assign  randomly from within our range to prevent inferences about in-flight security issues.
